### PR TITLE
WIP support lts-12 and GHC 8.4

### PR DESCRIPTION
**Pull request by tungd**
Hi, I'm working on updating the library to the latest LTS. So far I have got webapi and webapi-contract working. I'll continue working on the remaining packages over the weekend.

### CODE REVIEW

**Review by ersran9 — CHANGES_REQUESTED** [review]
Thanks for the PR!  Just a couple of things - 

* As a public project we would like to support both stack and cabal. Moreover we use `webapi` internally with nix too. This means we would like to to use `.cabal` file instead of using a `project.yaml`. 
*  Along with the updated `stack.yaml` which points at lts-12.14, is it possible to have the old stack file also (renamed to something else - say `stack-ghc-8.yaml`). This way users of `ghc-8.0.x` are still able to use it.

**Comment by tungd** [comment]
Sure, I'll update the PR.

**Comment by tungd** [comment]
Hi, I've updated the PR accordingly. Please check. 🍺 
Btw, there's a lot more work to support `webapi-swagger` and `webapi-docs`.

**Review by ersran9 — APPROVED** [review]

**Comment by ersran9** [comment]
Thanks a lot!

**Pull request merged**
